a = int(input("Give me a first number: "))
b = int(input("Give me a second number: "))
print("Thank you!")
print(f"{a} + {b} = {a + b} ")
print(f"{a} - {b} = {a - b} ")
print(f"{a} / {b} = {a / b} ")
print(f"{a} * {b} = {a * b} ")